"""empty message

Revision ID: d1aa19ab426c
Revises: 
Create Date: 2024-03-21 13:56:41.628491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1aa19ab426c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(), nullable=False),
    sa.Column('last', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('itinerary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('groupType', sa.String(), nullable=True),
    sa.Column('groupSize', sa.Integer(), nullable=True),
    sa.Column('dates', sa.Integer(), nullable=False),
    sa.Column('food', sa.String(), nullable=True),
    sa.Column('entertainment', sa.String(), nullable=True),
    sa.Column('nightlife', sa.String(), nullable=True),
    sa.Column('culture', sa.String(), nullable=True),
    sa.Column('flightPrice', sa.Integer(), nullable=True),
    sa.Column('flightStops', sa.Integer(), nullable=True),
    sa.Column('flightAirline', sa.String(), nullable=True),
    sa.Column('hotelPrice', sa.Integer(), nullable=True),
    sa.Column('hotelRating', sa.Integer(), nullable=True),
    sa.Column('hotelLocation', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('fk_trips_table_user_id_user_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
